# Generated by Django 4.1.4 on 2022-12-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_pourcatange'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pricenet',
            field=models.FloatField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
