# Generated by Django 4.1.3 on 2022-12-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_category_image_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pourcatange',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
